INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (1, 'Boston Celtics', 1946, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (2, 'Chicago Stags', 1946, 1949.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (3, 'Cleveland Rebels', 1946, 1946.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (4, 'Detroit Falcons', 1946, 1946.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (5, 'Golden State Warriors', 1946, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (6, 'New York Knicks', 1946, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (7, 'Pittsburgh Ironmen', 1946, 1946.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (8, 'Providence Steamrollers', 1946, 1948.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (9, 'St. Louis Bombers', 1946, 1949.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (10, 'Toronto Huskies', 1946, 1946.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (11, 'Washington Capitols', 1946, 1950.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (12, 'Baltimore Bullets', 1947, 1954.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (13, 'Detroit Pistons', 1948, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (14, 'Indianapolis Jets', 1948, 1948.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (15, 'Los Angeles Lakers', 1948, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (16, 'Sacramento Kings', 1948, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (17, 'Anderson Packers', 1949, 1949.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (18, 'Atlanta Hawks', 1949, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (19, 'Denver Nuggets', 1949, 1949.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (20, 'Indianapolis Olympians', 1949, 1952.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (21, 'Philadelphia 76ers', 1949, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (22, 'Sheboygan Red Skins', 1949, 1949.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (23, 'Waterloo Hawks', 1949, 1949.0, 0);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (24, 'Washington Wizards', 1961, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (25, 'Chicago Bulls', 1966, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (26, 'Houston Rockets', 1967, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (27, 'Oklahoma City Thunder', 1967, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (28, 'Milwaukee Bucks', 1968, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (29, 'Phoenix Suns', 1968, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (30, 'Cleveland Cavaliers', 1970, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (31, 'Los Angeles Clippers', 1970, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (32, 'Portland Trail Blazers', 1970, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (33, 'Utah Jazz', 1974, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (34, 'Brooklyn Nets', 1976, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (35, 'Denver Nuggets', 1976, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (36, 'Indianapolis Pacers', 1976, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (37, 'San Antonio Spurs', 1976, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (38, 'Dallas Mavericks', 1980, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (39, 'Charlotte Hornets', 1988, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (40, 'Miami Heat', 1988, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (41, 'Minnesota Timberwolves', 1989, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (42, 'Orlando Magic', 1989, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (43, 'Memphis Grizzlies', 1995, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (44, 'Toronto Raptors', 1995, NULL, 1);
INSERT INTO franchises (id, most_recent_name, year_founded, year_folded, is_active) VALUES (45, 'New Orleans Pelicans', 2002, NULL, 1);
