INSERT INTO teams (id, name, franchise_id) VALUES (1, 'Toronto Huskies', 10.0);
INSERT INTO teams (id, name, franchise_id) VALUES (2, 'St. Louis Bombers', 9.0);
INSERT INTO teams (id, name, franchise_id) VALUES (3, 'Providence Steamrollers', 8.0);
INSERT INTO teams (id, name, franchise_id) VALUES (4, 'Chicago Stags', 2.0);
INSERT INTO teams (id, name, franchise_id) VALUES (5, 'Detroit Falcons', 4.0);
INSERT INTO teams (id, name, franchise_id) VALUES (6, 'Cleveland Rebels', 3.0);
INSERT INTO teams (id, name, franchise_id) VALUES (7, 'Pittsburgh Ironmen', 7.0);
INSERT INTO teams (id, name, franchise_id) VALUES (8, 'Boston Celtics', 1.0);
INSERT INTO teams (id, name, franchise_id) VALUES (9, 'Philadelphia Warriors', 5.0);
INSERT INTO teams (id, name, franchise_id) VALUES (10, 'New York Knicks', 6.0);
INSERT INTO teams (id, name, franchise_id) VALUES (11, 'Washington Capitols', 11.0);
INSERT INTO teams (id, name, franchise_id) VALUES (12, 'Baltimore Bullets', 12.0);
INSERT INTO teams (id, name, franchise_id) VALUES (13, 'Indianapolis Jets', 14.0);
INSERT INTO teams (id, name, franchise_id) VALUES (14, 'Ft. Wayne Zollner Pistons', 13.0);
INSERT INTO teams (id, name, franchise_id) VALUES (15, 'Rochester Royals', 16.0);
INSERT INTO teams (id, name, franchise_id) VALUES (16, 'Minneapolis Lakers', 15.0);
INSERT INTO teams (id, name, franchise_id) VALUES (17, 'Tri-Cities Blackhawks', 18.0);
INSERT INTO teams (id, name, franchise_id) VALUES (18, 'Indianapolis Olympians', 20.0);
INSERT INTO teams (id, name, franchise_id) VALUES (19, 'Waterloo Hawks', 23.0);
INSERT INTO teams (id, name, franchise_id) VALUES (20, 'Anderson Packers', 17.0);
INSERT INTO teams (id, name, franchise_id) VALUES (21, 'Sheboygan Redskins', 22.0);
INSERT INTO teams (id, name, franchise_id) VALUES (22, 'Syracuse Nationals', 21.0);
INSERT INTO teams (id, name, franchise_id) VALUES (23, 'Denver Nuggets', 19.0);
INSERT INTO teams (id, name, franchise_id) VALUES (24, 'East NBA All Stars East', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (25, 'Milwaukee Hawks', 18.0);
INSERT INTO teams (id, name, franchise_id) VALUES (26, 'St. Louis Hawks', 18.0);
INSERT INTO teams (id, name, franchise_id) VALUES (27, 'Detroit Pistons', 13.0);
INSERT INTO teams (id, name, franchise_id) VALUES (28, 'Cincinnati Royals', 16.0);
INSERT INTO teams (id, name, franchise_id) VALUES (29, 'West NBA All Stars West', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (30, 'Los Angeles Lakers', 15.0);
INSERT INTO teams (id, name, franchise_id) VALUES (31, 'Chicago Zephyrs', 24.0);
INSERT INTO teams (id, name, franchise_id) VALUES (32, 'San Francisco Warriors', 5.0);
INSERT INTO teams (id, name, franchise_id) VALUES (33, 'Philadelphia 76ers', 21.0);
INSERT INTO teams (id, name, franchise_id) VALUES (34, 'Chicago Bulls', 25.0);
INSERT INTO teams (id, name, franchise_id) VALUES (35, 'San Diego Rockets', 26.0);
INSERT INTO teams (id, name, franchise_id) VALUES (36, 'Seattle SuperSonics', 27.0);
INSERT INTO teams (id, name, franchise_id) VALUES (37, 'Atlanta Hawks', 18.0);
INSERT INTO teams (id, name, franchise_id) VALUES (38, 'Milwaukee Bucks', 28.0);
INSERT INTO teams (id, name, franchise_id) VALUES (39, 'Phoenix Suns', 29.0);
INSERT INTO teams (id, name, franchise_id) VALUES (40, 'Buffalo Braves', 31.0);
INSERT INTO teams (id, name, franchise_id) VALUES (41, 'Houston Rockets', 26.0);
INSERT INTO teams (id, name, franchise_id) VALUES (42, 'Portland Trail Blazers', 32.0);
INSERT INTO teams (id, name, franchise_id) VALUES (43, 'Cleveland Cavaliers', 30.0);
INSERT INTO teams (id, name, franchise_id) VALUES (44, 'Golden State Warriors', 5.0);
INSERT INTO teams (id, name, franchise_id) VALUES (45, 'Kansas City-Omaha Kings', 16.0);
INSERT INTO teams (id, name, franchise_id) VALUES (46, 'Capital Bullets', 24.0);
INSERT INTO teams (id, name, franchise_id) VALUES (47, 'Washington Bullets', 24.0);
INSERT INTO teams (id, name, franchise_id) VALUES (48, 'New Orleans Jazz', 33.0);
INSERT INTO teams (id, name, franchise_id) VALUES (49, 'San Antonio Spurs', 37.0);
INSERT INTO teams (id, name, franchise_id) VALUES (50, 'Indiana Pacers', 36.0);
INSERT INTO teams (id, name, franchise_id) VALUES (51, 'New Jersey Nets', 34.0);
INSERT INTO teams (id, name, franchise_id) VALUES (52, 'Kansas City Kings', 16.0);
INSERT INTO teams (id, name, franchise_id) VALUES (53, 'San Diego Clippers', 31.0);
INSERT INTO teams (id, name, franchise_id) VALUES (54, 'Utah Jazz', 33.0);
INSERT INTO teams (id, name, franchise_id) VALUES (55, 'Dallas Mavericks', 38.0);
INSERT INTO teams (id, name, franchise_id) VALUES (56, 'Denver Nuggets', 35.0);
INSERT INTO teams (id, name, franchise_id) VALUES (57, 'Los Angeles Clippers', 30.0);
INSERT INTO teams (id, name, franchise_id) VALUES (58, 'Sacramento Kings', 16.0);
INSERT INTO teams (id, name, franchise_id) VALUES (59, 'Charlotte Hornets', 39.0);
INSERT INTO teams (id, name, franchise_id) VALUES (60, 'Miami Heat', 40.0);
INSERT INTO teams (id, name, franchise_id) VALUES (61, 'Orlando Magic', 42.0);
INSERT INTO teams (id, name, franchise_id) VALUES (62, 'Minnesota Timberwolves', 41.0);
INSERT INTO teams (id, name, franchise_id) VALUES (63, 'Toronto Raptors', 44.0);
INSERT INTO teams (id, name, franchise_id) VALUES (64, 'Vancouver Grizzlies', 43.0);
INSERT INTO teams (id, name, franchise_id) VALUES (65, 'Washington Wizards', 24.0);
INSERT INTO teams (id, name, franchise_id) VALUES (66, 'Memphis Grizzlies', 43.0);
INSERT INTO teams (id, name, franchise_id) VALUES (67, 'New Orleans Hornets', 45.0);
INSERT INTO teams (id, name, franchise_id) VALUES (68, 'Charlotte Bobcats', 39.0);
INSERT INTO teams (id, name, franchise_id) VALUES (69, 'New Orleans/Oklahoma City Hornets', 45.0);
INSERT INTO teams (id, name, franchise_id) VALUES (70, 'Lyon-Villeurbanne Adecco ASVEL', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (71, 'Barcelona Winterthur FC', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (72, 'Roma Virtus Lottomatica', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (73, 'Khimki BC', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (74, 'Tel Aviv Maccabi Elite', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (75, 'Istanbul Efes Pilsen', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (76, 'Lottomatica Lottomatica Roma', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (77, 'Unicaja Malaga Unicaja Malaga', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (78, 'MMT Estudiantes MMT Estudiantes', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (79, 'Real Madrid Real Madrid', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (80, 'China Team China', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (81, 'Oklahoma City Thunder', 27.0);
INSERT INTO teams (id, name, franchise_id) VALUES (82, 'Barcelona Regal FC', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (83, 'Milano Armani Jeans Milano', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (84, 'Istanbul Fenerbahce Ulker', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (85, 'Berlin Alba Berlin', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (86, 'Milano EA7 Emporio Armani Milano', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (87, 'Barcelona FC Barcelona Regal', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (88, 'Brooklyn Nets', 34.0);
INSERT INTO teams (id, name, franchise_id) VALUES (89, 'New Orleans Pelicans', 45.0);
INSERT INTO teams (id, name, franchise_id) VALUES (90, 'Bilbao Basket', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (91, 'LA Clippers', 31.0);
INSERT INTO teams (id, name, franchise_id) VALUES (92, 'Milano Olimpia Milano', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (93, 'Madrid Real Madrid', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (94, 'Flamengo Flamengo', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (95, 'Barcelona FC Barcelona Lassa', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (96, 'Team Stephen', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (97, 'Team Giannis', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (98, 'Team Durant', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (99, 'Team LeBron', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (100, 'Moscow CSKA', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (101, 'Panathinaikos Panathinaikos', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (102, 'Zalgiris Kaunas Zalgiris Kaunas', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (103, 'Vilnius Lietuvos Rytas', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (104, 'Belegrade Partizan', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (105, 'Athens Olympiacos', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (106, 'Haifa Maccabi Haifa', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (107, 'Vitoria Caja Laboral', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (108, 'Siena Montepaschi Siena', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (109, 'Tel Aviv Maccabi Electra', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (110, 'Istanbul Fenerbahce Sports Club', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (111, 'Bauru Paschoalotto/Bauru', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (112, 'Shanghai Shanghai Sharks', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (113, 'Buenos Aires San Lorenzo', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (114, 'Guangzhou Long-Lions', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (115, 'Sydney Kings', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (116, 'Shanghai Sharks', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (117, 'Melbourne United', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (118, 'Brisbane Bullets', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (119, 'Ra''anana Maccabi Ra''anana', NULL);
INSERT INTO teams (id, name, franchise_id) VALUES (120, 'Adelaide 36ers', NULL);
